def up(cursor, bot):
    cursor.execute(
        """
    CREATE TABLE "user" (
        discord_id TEXT PRIMARY KEY NOT NULL,
        points INT NOT NULL DEFAULT 0,
        level INT NOT NULL DEFAULT 100,
        user_name TEXT NOT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE "message" (
        message_id TEXT PRIMARY KEY NOT NULL,   
        user_id TEXT NOT NULL REFERENCES "user"(discord_id),
        channel_id TEXT,
        content TEXT NOT NULL,
        time_sent timestamp with time zone,
        credited BOOLEAN DEFAULT FALSE
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE command (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        level INT NOT NULL,
        action TEXT DEFAULT NULL,
        extra_args TEXT DEFAULT NULL,
        command TEXT NOT NULL,
        description TEXT DEFAULT NULL,
        delay_all INT NOT NULL,
        delay_user INT NOT NULL,
        enabled BOOLEAN NOT NULL,
        cost INT NOT NULL,
        can_execute_with_whisper BOOLEAN DEFAULT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE command_data (
        command_id INT PRIMARY KEY NOT NULL REFERENCES "command"(id) ON DELETE CASCADE,
        num_uses INT NOT NULL,
        added_by TEXT DEFAULT NULL,
        edited_by TEXT DEFAULT NULL,
        last_date_used TIMESTAMPTZ DEFAULT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE command_example (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ON DELETE CASCADE,
        command_id INT NOT NULL REFERENCES "command"(id),
        title TEXT NOT NULL,
        chat TEXT NOT NULL,
        description TEXT NOT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE "module" (
        id TEXT PRIMARY KEY NOT NULL,   
        enabled BOOLEAN NOT NULL DEFAULT FALSE,
        settings TEXT
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE banphrase (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        phrase TEXT NOT NULL,
        length INT NOT NULL,
        permanent BOOLEAN NOT NULL,
        warning BOOLEAN NOT NULL,
        notify BOOLEAN NOT NULL,
        case_sensitive BOOLEAN NOT NULL,
        enabled BOOLEAN NOT NULL,
        operator TEXT NOT NULL DEFAULT 'contains',
        sub_immunity BOOLEAN NOT NULL DEFAULT FALSE,
        remove_accents BOOLEAN NOT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE banphrase_data (
        banphrase_id INT PRIMARY KEY NOT NULL REFERENCES banphrase(id) ON DELETE CASCADE,
        num_uses INT NOT NULL,
        added_by TEXT DEFAULT NULL,
        edited_by TEXT DEFAULT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE timer (
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        action TEXT NOT NULL,
        interval_online INT NOT NULL,
        interval_offline INT NOT NULL,
        enabled BOOLEAN NOT NULL
    )
    """
    )

    cursor.execute(
        """
    CREATE TABLE admin_log_entry(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        type TEXT NOT NULL,
        user_id TEXT REFERENCES "user"(discord_id) ON DELETE SET NULL,
        message TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL,
        data JSONB NOT NULL
    )
    """
    )
    cursor.execute("CREATE INDEX ON admin_log_entry(created_at)")
