def up(cursor, bot):
    cursor.execute(
        """
    CREATE TABLE timeouts(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT REFERENCES "user"(discord_id) ON DELETE CASCADE NOT NULL,
        issued_by TEXT REFERENCES "user"(discord_id) ON DELETE SET NULL,
        until TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL,
    )
    """
    )
