def up(cursor, bot):
    cursor.execute(
        """
    CREATE TABLE giveaways(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        started_by_id TEXT REFERENCES "user"(discord_id) ON DELETE SET NULL,
        ended_by_id TEXT REFERENCES "user"(discord_id) ON DELETE SET NULL,
        giveaway_deadline TEXT NOT NULL,
        giveaway_item TEXT NOT NULL,
        locked BOOLEAN NOT NULL DEFAULT FALSE,
        winner_id TEXT REFERENCES "user"(discord_id) ON DELETE SET NULL,
        enabled BOOLEAN NOT NULL DEFAULT FALSE
    )
    """
    )
    cursor.execute(
        """
    CREATE TABLE giveaway_entries(
        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT REFERENCES "user"(discord_id) ON DELETE CASCADE,
        giveaway_id INT REFERENCES "giveaways"(id) ON DELETE CASCADE,
        date_entered TIMESTAMPTZ NOT NULL,
        tickets INT NOT NULL DEFAULT 1
    )
    """
    )
